#requires -Version 5.1
# Capture only; no HID packets are generated by this script.
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidatePattern('^\d{3}_[a-z0-9_]+$')][string]$Name,
    [ValidateRange(5,180)][int]$Seconds = 60
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$project = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path
$captureDir = Join-Path $project ('captures\' + $Name)
if (Test-Path -LiteralPath $captureDir) { throw 'Refusing to overwrite a capture directory.' }
New-Item -ItemType Directory -Path $captureDir | Out-Null
$env:WIRESHARK_EXTCAP_DIR = Join-Path $PSScriptRoot 'extcap'
$tshark = 'C:\Program Files\Wireshark\tshark.exe'
# USBPcap2/address 5 verified in the initial descriptor probe on this session.
# Re-enumerate topology if the keyboard is disconnected or the host is restarted.
$captureArgs = @('-i','\\.\USBPcap2',
    '-o','extcap.____usbpcap2.capturefromalldevices:false',
    '-o','extcap.____usbpcap2.capturefromnewdevices:false',
    '-o','extcap.____usbpcap2.devices:5',
    '-o','extcap.____usbpcap2.injectdescriptors:true',
    '-a',('duration:' + $Seconds),'-w',(Join-Path $captureDir 'traffic.pcapng'))
$record = [ordered]@{executable=$tshark; arguments=$captureArgs; requestedAtUtc=[DateTime]::UtcNow.ToString('o'); finishedAtUtc=$null; exitCode=$null; descriptorInjection=$true; topologyMustBeReverifiedAfterReconnect=$true}
$record | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $captureDir 'capture-command.json') -Encoding utf8
$ErrorActionPreference = 'Continue'
& $tshark @captureArgs 2>&1 | Tee-Object -FilePath (Join-Path $captureDir 'capture.log')
$record.exitCode=$LASTEXITCODE
$record.finishedAtUtc=[DateTime]::UtcNow.ToString('o')
$record | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath (Join-Path $captureDir 'capture-command.json') -Encoding utf8
exit $record.exitCode
